export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { Services } from './Services'
export { Projects } from './Projects'
export { Contact } from './Contact'
export { Footer } from './Footer'
